### ISSUE TITLE
Unicode paths bug

### ISSUE THREAD

**Issue by nhanqv** [kefir500/apk-icon-editor#25]
Dear Kefir500,

First of all, thank you very much for the great tool.
But whenever I press "Pack APK" button and I receive a warning:
"APK packed with the following warnings:
- APK is not signed.
- APK is not optimized."

I have installed JDK for signing APK. But the warning is still existed.
And when I install this APK file into my tablet using adb tools, I received the following error:
"INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION"

Please help me to fix the warning above.

Thank you very much

**Comment by kefir500** [comment]
Hi,

Could you please provide the contents of the logfile located at **%LOCALAPPDATA%\apk-icon-editor\apk-icon-editor.log** (after repeating steps to cause this error)?

**Comment by nhanqv** [comment]
Thank you for your support.

I read the log file and found the problem. Because path to temp.apk consists of Unicode characters.
I have changed path to temp.apk.

Please fix this bugs in the next release.

Thanks

**Comment by kefir500** [comment]
Strange,
Once, there was a similar problem with Unicode characters, but the bug was fixed.
I believe some unhandled characters are still there.

Could you please write below (or email me) the problematic Unicode path, so I could check in on my machine?

Thanks a lot for your feedback.

**Comment by nhanqv** [comment]
The unicode characters is Vietnamese characters. Thank you very much

**Comment by kefir500** [comment]
It turned out that Java CLI for Windows can not handle Unicode characters. "APK Icon Editor" uses Java for Apktool, signing and optimizing (zipalign). These features use temporary directory for current user, so if the the username consists of Unicode characters, they fail. The workaround is to change the temporary directory. This feature is implemented in the latest [APK Icon Editor v1.4.0](http://kefir500.github.io/apk-icon-editor/download).
