### ISSUE TITLE
apk tool error

### ISSUE THREAD

**Issue by usman76** [kefir500/apk-icon-editor#32]
[10:29:52] APK Icon Editor v1.5.0 
[10:29:52] Initializing... 
[10:29:52] Starting...
 
[10:29:53] "JRE" 32-bit found: 
[10:29:53] "Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'
has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment." 
[10:29:53] "JDK" 32-bit found: 
[10:29:53] "javac 1.7.0_79" 
[10:29:53] Language set to "en"

**Comment by kefir500** [comment]
Seems that you your registry is messed up with different Java versions (1.7 and 1.8). Try uninstalling all of your current Java Runtime Environments, then install [JRE 1.8 (32 bit)](http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jre-8u60-windows-i586.exe).

If this still does not help, Google for: `Registry key 'Software\JavaSoft\Java Runtime Environment\CurrentVersion' has value '1.8', but '1.7' is required`. This is a common problem caused by faulty Java installation.

**Comment by menelaosbgr** [comment]
I had this error on some windows services running Java. In the end, the solution was to uninstall the other versions of java and leave 1.8.
