### ISSUE TITLE
Portable Java

### ISSUE THREAD

**Issue by sick13** [kefir500/apk-icon-editor#52]
Can the program be made to recognize Java portable? example i have it in G:\ Drive added Java portable to Environment path but Apk Icon Editor does not recognize it.

**Comment by sick13** [comment]
Never mind, added the wrong folder in Windows, it shoud point to BIN folder rather then Java
works great!

**Comment by kefir500** [comment]
You are right, while such environment variables as `JAVA_HOME`, `JRE_HOME`, `JDK_HOME`, etc. point to the Java general directories, the `PATH` environment variable should contain the Java `bin` subdirectory in order to properly find the needed executable.

Glad you got the problem resolved!
Closing the issue.
