### ISSUE TITLE
App isn't changing icon on Fire TV "My Apps & Games"

### ISSUE THREAD

**Issue by Benman2785** [kefir500/apk-icon-editor#58]
hi, i try this app (v1.7.1) and it worked partly

it changed the icon - but the firetv doesnt use it correctly in the Apps drawer - there it only uses the square item

oh and can you add the possibility to remove icons?

**Comment by kefir500** [comment]
Hi, did you add/change the TV banner image besides the standard icons?
See the [screenshot](https://user-images.githubusercontent.com/3617499/31858635-43a78b66-b71e-11e7-9ca0-2f4896b7025e.png).

**Comment by Benman2785** [comment]
nope - i think i didnt

what resolution does they need=

sry for late answer

**Comment by kefir500** [comment]
According to [these](https://developer.amazon.com/docs/app-submission/asset-guidelines.html#firetvassets) guidelines, the required size is 1280x720.

**Comment by Benman2785** [comment]
thank you - i test now :)

**Comment by Benman2785** [comment]
still persists 
http://benmanshafen.de/downloads/aftv/icon_error.jpg

**Comment by kefir500** [comment]
There is a possibility that Fire TV now pulls banners *only* from the Amazon Appstore. Unfortunately, I can't check this information due to lack of the device. Are there any sideloaded APK application that **do** display the altered icon/banner?

**Comment by Benman2785** [comment]
i found out that when i install the apks with "wm density 320" i have fullsize icons - but square and not 16:9

**Comment by Benman2785** [comment]
if you want i can buy you an FireTV Stick ;)

**Comment by kefir500** [comment]
Hi again, did you find any *sideloaded* APK applications that **do** display the altered icon/banner as I asked before?

Also, I moved your second question in a separate [issue](65). The feature is implemented, I will commit the code soon.

**Comment by Benman2785** [comment]
it looks like amazon is now loading those icons from its own webserver

i can use your programm to create an icon that is shown correct in the "last used" list - but it wont show on the APP tab

so i think its Amazon that broke it

yet again, thank you for your help

**Comment by kefir500** [comment]
Yes, I also came across [this post](https://forums.developer.amazon.com/questions/483/how-to-provide-the-firetv-and-firetv-stick-app-ban.html): seems that the TV banners can only be submitted while uploading the app to Amazon Store (i.e. there is no way to manually edit the APK).

So for now I will close this issue. If you come across the side-loaded APK which has the proper banner, feel free to reopen it, and I will definitely add the needed feature :)

Thank you for your cooperation.

**Comment by Benman2785** [comment]
ok - now im not 100% sure
it only makes the icon small when it updates the device while the density is not 320
so if i have correct density while installing i will have a correct icon - but its square - and not 16:9

so maybe you need to add the correct option of 1280x720 specific for FireTVs
because now it simply streches the 1280x720 icon into a square

as i said - i would buy you and FireTV stick so that you can test

**Comment by ibuprophen1** [comment]
@Benman2785, did you try another apk that has this already and compare it to the one you're trying? 

Just a suggestion to, hopefully, help out... :-) 


~Ibuprophen

**Comment by Benman2785** [comment]
![icon_error_2](https://user-images.githubusercontent.com/21282980/39098582-3de36900-466d-11e8-91fe-0e9ae0170962.jpg)
http://benmanshafen.de/downloads/aftv/icon_error_2.jpg

as shown here - the SKY icon looks fine (like all other icons) - but i have to remove the background of the png
otherwise it will look like the icon right to "maxdome" on first row - it isnt stretched, but a square - because it will force the resolution that the icon is set to - even if you use a 1280x720 icon

**Comment by Benman2785** [comment]
@kefir500 pls reopen

i am 66% sure that the FireTV forces the icon (what ever size it is) into the fixed aspect-ratio of the icon setting (like XXXHDPI 192x192 - results in a SQUARE icon - even if file is 1280x720)

**Comment by ibuprophen1** [comment]
@Benman2785, have you tried the following? 

Create the addition for the FireTV icon then open the decompiled app and just replace the icon there with the appropriate "XXXHDPI..." directory with the correct dimensions? 

This is just a suggestion... :-)

**Comment by kefir500** [comment]
@Benman2785 Amazon devices fetch icons and banners in a different way compared to the Android standard methods.

As I mentioned before, Amazon devices retrieve icons and banners **from their own servers**. That means that the Amazon APK files themselves **don't** contain the proper drawable resources: these resources are submitted by the developer when uploading his application to Amazon Store. The same situation also applies to Amazon Kindle/Fire tablets where the large carousel icons are fetched from their own servers. However, if the application is side-loaded (i. e. comes not from the Amazon Store) and the needed drawables loaded from server are missing, Amazon devices fetch the icon/banner from the internal standard APK resources **which results in improper scaling**. Amazon Kindle/Fire tablets carousel is also scaled, however its icons are square as well as the Android standard ones, that's why this little hack (replacing the default icons) used by APK Icon Editor works well on those devices.

The default sizes used in APK Icon Editor are just suggestions for optional icon resizing; the resulting icon sizes **are not affected** if you discard the option to automatically resize the icon. So the icons are stretched to default square sizes by the Android itself.

I may be missing something, so if you find the side-loaded APK with a proper icons, send it (here or by email) please. However, **seems that there is no possibility to set the properly sized icons** because of the Amazon resource fetching methods.

**Comment by Benman2785** [comment]
ok ;)
two ways to deal with this:
1. host a server in my lan that contains the icon and reroute the request to this server - than i need the correct address and way of naming the file
2. live with it (bob up and down while crying)

funny is that the internal icon works correct in "recent" but not in "my apps"
but its ok for that 3 apps i need it

thank you
