### ISSUE TITLE
Apktool mode not available

### ISSUE THREAD

**Issue by paultnp** [kefir500/apk-icon-editor#60]
Hi,
 I am trying to change the name of an android app. When I drop the .apk file in the "APK Icon Editor" Mac app, it extracts and shows the app icon of all sizes. I can also see the App name and version in the property Tab, but are not editable. On the property tab it shows a message "To edit application name and version switch to APK tool mode".

I have already  run below two commands on the terminal in the Mac to install apktool.
**"ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null"**

and 

**brew install apktool**

The apktool installs successfully and terminal also now recognise the "apktool" command, but the "APK Icon Editor" Mac app still doesn't show the "APK tool Mode" option so that I can change App Name.

Thanks
Teena Nath Paul

**Comment by kefir500** [comment]
Sorry for the delay.

There is no need to install Apktool separately, it is already present in the APK Icon Editor distribution. You just need to click **Settings –> Repacking** (or simply press <kbd>Ctrl</kbd>+<kbd>P</kbd>) and check the **Use Apktool repacking** in order to switch to Apktool mode.
