### ISSUE TITLE
AFH Feature Question/Recommendation... 

### ISSUE THREAD

**Issue by ibuprophen1** [kefir500/apk-icon-editor#68]
Hello @kefir500, 

I can't believe that I've been wanting to ask this question for a while but, keep forgetting... 

I am aware of the "Cloud storage upload" feature for Dropbox, Google Drive, Microsoft OneDrive, etc... 

I'm just wondering if it's possible to add the "AndroidFileHost" to this? 

Thanks a bunch! :-) 

~Ibuprophen

**Comment by kefir500** [comment]
Hi,

Doesn't seem that their [API](https://androidfilehost.com/api/docs/) supports `OAuth` or similar authentication methods which are used as a base for cloud uploads by APK Icon Editor.

I contacted their support, probably they will give an exact answer.

**Comment by ibuprophen1** [comment]
I'm not sure if you're aware of the following... 

The following is the Official Google+ profile for AFH... 
https://plus.google.com/communities/101143921551874060164

The following is the Official Google+ Profile for the Lead AFH Administrator (Alex P)... 
https://plus.google.com/115686626910297469891

The following is the Official (Primary/Main) AFH Gmail address... 
staff@androidfilehost.com

I do know that they're all good because I have successfully communicated with AFH using them all. 

Thanks a bunch! :-) 


~Ibuprophen

**Comment by ibuprophen1** [comment]
@kefir500, have you been able to make any progress with this? 

I'd state that the best way to implementing this feature is to add the separate AFH FTP & AFH SFTP options since the settings being used for them (separately) are the same but, would require a login after S/FTP Access would have to be requested with a separate login that's tied to the same account. 

If you require additional information, please let me know my friend! :-) 


~Ibuprophen

**Comment by kefir500** [comment]
As mentioned previously, AFH API does not support **OAuth**. APK Icon Editor uses the [`Cloud`](https://github.com/kefir500/apk-icon-editor/blob/master/src/core/cloud.cpp) class which is based on **OAuth** authentication, so in order to support AFH, an additional class supporting the FTP protocol (including the password storage, etc.) needs to be written.

In fact, I even thought of dropping the upload support: according to the stats, it is barely used. Also, many popular cloud services are still not supported by APK Icon Editor, not to mention AFH :)

Probably someday I will write a plugin system allowing to expand the upload services list regardless of authentication method, however (sorry to say) for now this not a priority task.

**Comment by ibuprophen1** [comment]
@kefir500, I agree with you regarding the upload feature... LOL! 

All the individuals that I know who use this software, never use this specific upload feature. 

I bet that if you removed this feature the software will noticeably reduce in size but, I'm just taking a guess at this. 

I appreciate your time, support and understanding with this My Friend! 👍 


~Ibuprophen
